### ISSUE TITLE
runtime execption

### ISSUE THREAD

**Issue by Onionuu** [chn-sunch/flutter_mycommunity_app#7]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building FutureBuilder<bool>(state:
_FutureBuilderState<bool>#532ce):
dependOnInheritedWidgetOfExactType<MediaQuery>() or dependOnInheritedElement() was called before
_IndexPageState.initState() completed.
When an inherited widget changes, for example if the value of Theme.of() changes, its dependent
widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor
or an initState() method, then the rebuilt dependent widget will not reflect the changes in the
inherited widget.
Typically references to inherited widgets should occur in widget build() methods. Alternatively,
initialization based on inherited widgets can be placed in the didChangeDependencies method, which
is called after initState and whenever the dependencies change thereafter.

The relevant error-causing widget was:
  FutureBuilder<bool>
  FutureBuilder:file:///E:/FlutterProject/flutter_mycommunity_app/lib/main.dart:210:12

When the exception was thrown, this was the stack:
#0      StatefulElement.dependOnInheritedElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:5007:9)
#1      StatefulElement.dependOnInheritedElement (package:flutter/src/widgets/framework.dart:5050:6)
#2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4185:14)
#3      MediaQuery.of (package:flutter/src/widgets/media_query.dart:860:20)
#4      ScreenUtil.init (package:flutter_screenutil/src/screen_util.dart:100:22)
#5      _IndexPageState.initState (package:flutter_app/page/index.dart:67:16)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4893:57)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3524:20)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#22     _invoke (dart:ui/hooks.dart:151:10)
#23     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#24     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by chn-sunch** [comment]
请问这个错误要怎么重现，我的flutter版本
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Tools • Dart 2.16.1 • DevTools 2.9.2
